services:
  - type: web
    name: deepshield-backend
    env: python
    region: ohio
    plan: starter # Starter plan min needed for 2GB RAM. Free tier will face OOM errors.
    rootDir: backend
    buildCommand: "./build.sh"
    startCommand: "uvicorn main:app --host 0.0.0.0 --port $PORT"
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.12
      - key: PORT
        value: 8000
